#!/bin/bash
#PBS -N preprocessing
#PBS -l walltime=02:00:00
#PBS -l mem=8gb
#PBS -l ncpus=4
#PBS -j oe
#PBS -o logs/preprocessing.log

echo "Job started: $(date)"

cd $PBS_O_WORKDIR

module add mambaforge
source /software/mambaforge/22.9.0-3/etc/profile.d/conda.sh
conda activate /storage/praha1/home/kalaluka_1550/.conda/envs/pvforecast

python notebooks/preprocessing.py

echo "Job finished: $(date)"
